auth:
  adminUser: Ubivius

postgresql: 
  postgresqlUsername: Ubivius

resources:
  requests:
    cpu: 500m
    memory: 1000Mi
  limits:
    cpu: 500m
    memory: 1000Mi

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - keycloak.admin.dev.ubivius.tk
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
